### ISSUE TITLE
Auto-import processes books, but they don't show up

### ISSUE THREAD

**Issue by mmonseurs** [crocodilestick/Calibre-Web-Automator#16]
When adding a new .epub to the ingest folder, the epub is deleted from that folder but does not show up in the web interface or on the filesystem. Adding the same book again results in the following:

```
[new-book-detector]: Removing john_scalzi_lockin.epub from import folder...
[new-book-detector]: john_scalzi_lockin.epub sucsessfully moved/converted, the Ingest Folder has been emptied and is ready
rm: cannot remove '/etc/calibre-web-automator/cwa-import/*': No such file or directory
[books-to-process]: New files detected - john_scalzi_lockin.epub
[new-book-processor]: Found 1 epub file(s) from the most recent download.
[new-book-detector]: New file detected: john_scalzi_lockin.epub
[new-book-processor]: Moving resulting files to calibre-web import folder...
[new-book-processor]: Moving /cwa-book-ingest/john_scalzi_lockin.epub...
[new-book-processor]: Copied 1 epub file(s) to calibre-web import folder.
[new-book-processor]: Processing of new files completed in 0.00 seconds.
[books-to-process]: New files sucsessfully moved/converted, the Ingest Folder has been emptied and is ready to go again.
The following books were not added as they already exist in the database (see --duplicates option or --automerge option):
  Lock In--A Novel of the Near Future
[new-book-detector] Added john_scalzi_lockin.epub to Calibre database
    /etc/calibre-web-automator/cwa-import/john_scalzi_lockin.epub
```

Seems like it's imported to the database, but the file itself is missing?

My docker-compose looks like the following:

```
---
services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/user/calibre-web/config:/config
      - /media/usenet/cwa-book-ingest:/cwa-book-ingest
      - /media/books:/calibre-main
    ports:
      - 8085:8083
    restart: unless-stopped
```

/media/books already contained a functioning database from a pre-existing (default) calibre-web instance.

Doesn't seem like a permissions issue either, /media/books is 1000:1002 with rwxrwxr-x, and container is run as 1000:1000. Same with /media/usenet/cwa-book-ingest.
